# Generated by Django 5.2.1 on 2025-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
