# Generated by Django 5.2.1 on 2025-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_alter_currentlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
